# Generated by Django 6.1 on 2026-08-24 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_cartitem'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('CUSTOMER_QR', 'Customer QR'), ('WAITER_MANUAL', 'Waiter manual')], default='CUSTOMER_QR', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='tables.customersession'),
        ),
    ]
