# Generated by Django 6.1 on 2026-08-25 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menuitemmodifiergroup_menuitemmodifieroption'),
        ('orders', '0003_order_source_alter_order_customer_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemModifierSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name_ky', models.CharField(max_length=255)),
                ('group_name_ru', models.CharField(max_length=255)),
                ('option_name_ky', models.CharField(max_length=255)),
                ('option_name_ru', models.CharField(max_length=255)),
                ('price_delta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('group_sort_order', models.PositiveIntegerField(default=0)),
                ('option_sort_order', models.PositiveIntegerField(default=0)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='orders.orderitem')),
            ],
            options={
                'ordering': ('group_sort_order', 'option_sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CartItemModifierSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier_selections', to='orders.cartitem')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_selections', to='menu.menuitemmodifiergroup')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_selections', to='menu.menuitemmodifieroption')),
            ],
            options={
                'ordering': ('group__sort_order', 'option__sort_order', 'id'),
                'constraints': [models.UniqueConstraint(fields=('cart_item', 'option'), name='unique_cart_item_modifier_option')],
            },
        ),
    ]
