# Generated by Django 6.1 on 2026-08-25 10:31

from django.db import migrations


def merge_equivalent_cart_lines(apps, schema_editor):
    cart_item_model = apps.get_model("orders", "CartItem")
    database_alias = schema_editor.connection.alias
    primary_items = {}

    cart_items = cart_item_model.objects.using(database_alias).order_by("id")
    for cart_item in cart_items.iterator():
        key = (
            cart_item.customer_session_id,
            cart_item.menu_item_id,
            cart_item.comment,
        )
        primary_item = primary_items.get(key)
        if primary_item is None:
            primary_items[key] = cart_item
            continue

        primary_item.quantity += cart_item.quantity
        primary_item.save(update_fields=("quantity",))
        cart_item.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitemmodifiersnapshot_cartitemmodifierselection'),
    ]

    operations = [
        migrations.RunPython(
            merge_equivalent_cart_lines,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveConstraint(
            model_name='cartitemmodifierselection',
            name='unique_cart_item_modifier_option',
        ),
        migrations.RemoveField(
            model_name='cartitemmodifierselection',
            name='cart_item',
        ),
        migrations.RemoveField(
            model_name='cartitemmodifierselection',
            name='group',
        ),
        migrations.RemoveField(
            model_name='cartitemmodifierselection',
            name='option',
        ),
        migrations.DeleteModel(
            name='OrderItemModifierSnapshot',
        ),
        migrations.DeleteModel(
            name='CartItemModifierSelection',
        ),
    ]
