# Generated by Django 6.1 on 2026-09-07 04:09

from django.db import migrations, models


def initialize_global_order_number_sequence(apps, schema_editor):
    order_model = apps.get_model("orders", "Order")
    sequence_model = apps.get_model("orders", "OrderNumberSequence")
    database_alias = schema_editor.connection.alias
    last_number = 0

    order_numbers = (
        order_model.objects.using(database_alias)
        .filter(order_number__startswith="ORD-")
        .values_list("order_number", flat=True)
    )
    for order_number in order_numbers.iterator():
        numeric_part = order_number[4:]
        if numeric_part.isdigit():
            last_number = max(last_number, int(numeric_part))

    sequence_model.objects.using(database_alias).create(
        scope="GLOBAL",
        last_number=last_number,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_cartitemmodifierselection_unique_cart_item_modifier_option_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNumberSequence',
            fields=[
                ('scope', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('last_number', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.RunPython(
            initialize_global_order_number_sequence,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
