# Generated by Django 6.1 on 2026-08-10 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_ky', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ('sort_order', 'name_ky'),
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_ky', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
                ('description_ky', models.TextField(blank=True)),
                ('description_ru', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/items/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingredients_ky', models.TextField(blank=True)),
                ('ingredients_ru', models.TextField(blank=True)),
                ('allergens_ky', models.TextField(blank=True)),
                ('allergens_ru', models.TextField(blank=True)),
                ('cooking_time_min', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='menu.category')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ('category', 'name_ky'),
            },
        ),
    ]
