# Generated by Django 6.1 on 2026-08-25 02:56

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0002_menuitem_sales_labels_and_prep_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuItemModifierGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name_ky", models.CharField(max_length=255)),
                ("name_ru", models.CharField(max_length=255)),
                (
                    "selection_type",
                    models.CharField(
                        choices=[("SINGLE", "Single"), ("MULTIPLE", "Multiple")],
                        max_length=8,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("min_selected", models.PositiveIntegerField(default=0)),
                (
                    "max_selected",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modifier_groups",
                        to="menu.menuitem",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "name_ky", "id"),
            },
        ),
        migrations.CreateModel(
            name="MenuItemModifierOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name_ky", models.CharField(max_length=255)),
                ("name_ru", models.CharField(max_length=255)),
                (
                    "price_delta",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.00")
                            )
                        ],
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_available", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="menu.menuitemmodifiergroup",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "name_ky", "id"),
            },
        ),
    ]
