# Generated by Django 6.1 on 2026-08-25 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menuitemmodifiergroup_menuitemmodifieroption'),
        ('orders', '0005_remove_cartitemmodifierselection_unique_cart_item_modifier_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitemmodifieroption',
            name='group',
        ),
        migrations.DeleteModel(
            name='MenuItemModifierGroup',
        ),
        migrations.DeleteModel(
            name='MenuItemModifierOption',
        ),
    ]
