from django.urls import path

from .views import (
    AcceptTableSessionView,
    AcceptWaiterCallView,
    AdminOrderDetailView,
    AdminOrdersView,
    AvailableTableSessionsView,
    CloseTableSessionView,
    CompleteWaiterCallView,
    KitchenOrdersView,
    ManualOrderCreateView,
    ManualOrderMenuItemsView,
    ManualOrderTablesView,
    MarkOrderDeliveredView,
    MarkOrderPreparingView,
    MarkOrderReadyView,
    MyOrdersView,
    MyTableSessionsView,
    PublicCartItemCreateView,
    PublicCartItemDetailView,
    PublicCartView,
    PublicOrderView,
    PublicWaiterCallCreateView,
    WaiterCallsView,
)


public_urlpatterns = [
    path(
        "qr/<uuid:qr_token>/cart/",
        PublicCartView.as_view(),
        name="public-cart",
    ),
    path(
        "qr/<uuid:qr_token>/cart/items/",
        PublicCartItemCreateView.as_view(),
        name="public-cart-item-create",
    ),
    path(
        "qr/<uuid:qr_token>/cart/items/<int:item_id>/",
        PublicCartItemDetailView.as_view(),
        name="public-cart-item-detail",
    ),
    path(
        "qr/<uuid:qr_token>/orders/",
        PublicOrderView.as_view(),
        name="public-orders",
    ),
    path(
        "qr/<uuid:qr_token>/waiter-calls/",
        PublicWaiterCallCreateView.as_view(),
        name="public-waiter-call-create",
    ),
]

waiter_urlpatterns = [
    path(
        "manual-order/tables/",
        ManualOrderTablesView.as_view(),
        name="waiter-manual-order-tables",
    ),
    path(
        "manual-order/menu-items/",
        ManualOrderMenuItemsView.as_view(),
        name="waiter-manual-order-menu-items",
    ),
    path(
        "manual-order/orders/",
        ManualOrderCreateView.as_view(),
        name="waiter-manual-order-create",
    ),
    path(
        "table-sessions/available/",
        AvailableTableSessionsView.as_view(),
        name="waiter-table-sessions-available",
    ),
    path(
        "table-sessions/my/",
        MyTableSessionsView.as_view(),
        name="waiter-table-sessions-my",
    ),
    path(
        "table-sessions/<int:session_id>/accept/",
        AcceptTableSessionView.as_view(),
        name="waiter-table-session-accept",
    ),
    path(
        "table-sessions/<int:session_id>/close/",
        CloseTableSessionView.as_view(),
        name="waiter-table-session-close",
    ),
    path(
        "orders/",
        MyOrdersView.as_view(),
        name="waiter-orders",
    ),
    path(
        "orders/<int:order_id>/delivered/",
        MarkOrderDeliveredView.as_view(),
        name="waiter-order-delivered",
    ),
    path(
        "calls/",
        WaiterCallsView.as_view(),
        name="waiter-calls",
    ),
    path(
        "calls/<int:call_id>/accept/",
        AcceptWaiterCallView.as_view(),
        name="waiter-call-accept",
    ),
    path(
        "calls/<int:call_id>/complete/",
        CompleteWaiterCallView.as_view(),
        name="waiter-call-complete",
    ),
]

kitchen_urlpatterns = [
    path(
        "orders/",
        KitchenOrdersView.as_view(),
        name="kitchen-orders",
    ),
    path(
        "orders/<int:order_id>/preparing/",
        MarkOrderPreparingView.as_view(),
        name="kitchen-order-preparing",
    ),
    path(
        "orders/<int:order_id>/ready/",
        MarkOrderReadyView.as_view(),
        name="kitchen-order-ready",
    ),
]

admin_urlpatterns = [
    path(
        "orders/",
        AdminOrdersView.as_view(),
        name="admin-orders",
    ),
    path(
        "orders/<int:order_id>/",
        AdminOrderDetailView.as_view(),
        name="admin-order-detail",
    ),
]

urlpatterns = public_urlpatterns
