"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import sys
from datetime import timedelta
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name, default):
    value = os.environ.get(name)
    if value is None:
        return default

    normalized_value = value.strip().lower()
    if normalized_value in {'1', 'true', 'yes', 'on'}:
        return True
    if normalized_value in {'0', 'false', 'no', 'off'}:
        return False

    raise ImproperlyConfigured(
        f'{name} must be one of: 1, true, yes, on, 0, false, no, off.'
    )


def env_int(name, default):
    value = os.environ.get(name)
    if value is None:
        return default

    try:
        return int(value.strip())
    except ValueError as error:
        raise ImproperlyConfigured(f'{name} must be an integer.') from error


def env_list(name, default):
    value = os.environ.get(name)
    if value is None:
        return list(default)
    return [item.strip() for item in value.split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', True)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured('SECRET_KEY must be set when DEBUG is False.')
    SECRET_KEY = 'django-insecure-3uk#107+yqzoj&!8rlaf=#a*ts#8i+&mjar0284p$7tsdks!6!'

ALLOWED_HOSTS = env_list('ALLOWED_HOSTS', ['localhost', '127.0.0.1'])

SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', False)
SESSION_COOKIE_SECURE = env_bool('SESSION_COOKIE_SECURE', not DEBUG)
CSRF_COOKIE_SECURE = env_bool('CSRF_COOKIE_SECURE', not DEBUG)

SECURE_HSTS_SECONDS = env_int('SECURE_HSTS_SECONDS', 0)
if SECURE_HSTS_SECONDS < 0:
    raise ImproperlyConfigured('SECURE_HSTS_SECONDS must not be negative.')
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(
    'SECURE_HSTS_INCLUDE_SUBDOMAINS',
    False,
)
SECURE_HSTS_PRELOAD = env_bool('SECURE_HSTS_PRELOAD', False)
SECURE_CONTENT_TYPE_NOSNIFF = env_bool('SECURE_CONTENT_TYPE_NOSNIFF', True)

SECURE_REFERRER_POLICY = os.environ.get(
    'SECURE_REFERRER_POLICY',
    'same-origin',
).strip()
if SECURE_REFERRER_POLICY not in {
    'no-referrer',
    'no-referrer-when-downgrade',
    'origin',
    'origin-when-cross-origin',
    'same-origin',
    'strict-origin',
    'strict-origin-when-cross-origin',
    'unsafe-url',
}:
    raise ImproperlyConfigured('SECURE_REFERRER_POLICY is invalid.')

X_FRAME_OPTIONS = os.environ.get('X_FRAME_OPTIONS', 'DENY').strip().upper()
if X_FRAME_OPTIONS not in {'DENY', 'SAMEORIGIN'}:
    raise ImproperlyConfigured('X_FRAME_OPTIONS must be DENY or SAMEORIGIN.')

if env_bool('SECURE_PROXY_SSL_HEADER', False):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'rest_framework',
    'drf_spectacular',
    'corsheaders',
    'phonenumber_field',
    'apps.common.apps.CommonConfig',
    'apps.users.apps.UsersConfig',
    'apps.restaurants.apps.RestaurantsConfig',
    'apps.menu.apps.MenuConfig',
    'apps.tables.apps.TablesConfig',
    'apps.orders.apps.OrdersConfig',
    'apps.notifications.apps.NotificationsConfig',
    'apps.analytics.apps.AnalyticsConfig',
]

AUTH_USER_MODEL = 'users.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Dastorkon API',
    'DESCRIPTION': 'QR menu and restaurant order-management MVP backend',
    'VERSION': '1.0.0',
    'ENUM_NAME_OVERRIDES': {
        'OrderStatusEnum': (
            ('NEW', 'New'),
            ('PREPARING', 'Preparing'),
            ('READY', 'Ready'),
            ('DELIVERED', 'Delivered'),
            ('COMPLETED', 'Completed'),
            ('CANCELLED', 'Cancelled'),
        ),
        'WaiterCallStatusEnum': (
            ('NEW', 'New'),
            ('ACCEPTED', 'Accepted'),
            ('DONE', 'Done'),
        ),
        'TableStatusEnum': (
            ('FREE', 'Free'),
            ('OCCUPIED', 'Occupied'),
        ),
        'TableSessionStatusEnum': (
            ('ACTIVE', 'Active'),
            ('CLOSED', 'Closed'),
        ),
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

PHONENUMBER_DEFAULT_REGION = 'KG'
PHONENUMBER_DB_FORMAT = 'E164'
PHONENUMBER_DEFAULT_FORMAT = 'E164'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

REDIS_URL = os.environ.get('REDIS_URL')
if REDIS_URL:
    CHANNEL_LAYERS['default'] = {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [REDIS_URL],
        },
    }


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL:
    DATABASES['default'] = dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=600,
        conn_health_checks=True,
    )


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CORS_ALLOWED_ORIGINS = env_list(
    'CORS_ALLOWED_ORIGINS',
    ['http://localhost:5173', 'http://127.0.0.1:5173'],
)
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = env_list('CSRF_TRUSTED_ORIGINS', [])

if "test" in sys.argv:
    PASSWORD_HASHERS = ["django.contrib.auth.hashers.MD5PasswordHasher"]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

email_backend = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend',
).strip()
if not email_backend:
    raise ImproperlyConfigured('EMAIL_BACKEND must not be empty.')

email_host = os.environ.get('EMAIL_HOST', 'localhost').strip()
email_port = env_int('EMAIL_PORT', 25)
if not 1 <= email_port <= 65535:
    raise ImproperlyConfigured('EMAIL_PORT must be between 1 and 65535.')

email_host_user = os.environ.get('EMAIL_HOST_USER', '')
email_host_password = os.environ.get('EMAIL_HOST_PASSWORD', '')
email_use_tls = env_bool('EMAIL_USE_TLS', False)
email_use_ssl = env_bool('EMAIL_USE_SSL', False)
if email_use_tls and email_use_ssl:
    raise ImproperlyConfigured(
        'EMAIL_USE_TLS and EMAIL_USE_SSL cannot both be True.'
    )

email_timeout = env_int('EMAIL_TIMEOUT', 10)
if email_timeout <= 0:
    raise ImproperlyConfigured('EMAIL_TIMEOUT must be greater than zero.')

MAILERS = {
    'default': {
        'BACKEND': email_backend,
    },
}

if email_backend == 'django.core.mail.backends.smtp.EmailBackend':
    MAILERS['default']['OPTIONS'] = {
        'host': email_host,
        'port': email_port,
        'username': email_host_user,
        'password': email_host_password,
        'use_tls': email_use_tls,
        'use_ssl': email_use_ssl,
        'timeout': email_timeout,
    }

DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'webmaster@localhost')
SERVER_EMAIL = os.environ.get('SERVER_EMAIL', 'root@localhost')
